aminueza/terraform-provider-minio

minio/provider.go

Hi,
For some ci/cd tools integration it will be a nice feature to configure the ```minio_server```,```minio_access_key``` and ```minio_secret_key``` by environment variables.

Configure the Minio Provider by environment variables

---

.github/workflows/docs.yml
README.md
docs/github/CODE_OF_CONDUCT.md

Hi,
At the moment the Markdowns contains two broken Links, like ```Use examples/main.tf to create some test config, such as:```
This additional Github Workflow validate the existing Markdown Files with [remarkjs/remark-validate-links](https://github.com/remarkjs/remark-validate-links#cli), [/nolte/github-action/markdown/validate](https://github.com/nolte/github-action/tree/master/markdown/validate).
Example Output: [nolte/terraform-provider-minio/runs](https://github.com/aminueza/terraform-provider-minio/runs/421710546)

validate markdown action

---

.devcontainer/Dockerfile
.devcontainer/activate-ssh-agent-on-linux-or-mac.sh
.devcontainer/activate-ssh-agent-on-windows.ps1
.devcontainer/devcontainer.json

Now we use our ssh key inside the container via VS Code SSH Agent bridge.
Also, add windows/mac/linux scripts to activate the ssh agent on host, in case it's not running yet.

Improve dev container image

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitpod.yml

So now we can use `mc` binary and also access AdminIO-UI that is auto-started on port `1234` (This port can be changed on Dockerfile `ENV ADMINIO_UI_PORT`).
References:
Minio Client (MC): https://github.com/minio/mc
AdminIO: https://github.com/rzrbld/adminio-ui

Add Minio Client (MC) and AdminIO to the DevContainer

---

minio/resource_minio_iam_user.go

I'm not sure if this is correct, I based this on the bucket import code and it seems to be working, at least when using the basic example in #90.
https://github.com/aminueza/terraform-provider-minio/blob/b8557a4c2b19039dc8575713dcba166ba6f74632/minio/resource_minio_s3_bucket.go#L121-L144
`iamUserConfig.MinioIAMName` is not populated at that time if the resource is not present in the tfstate.
This currently only reads the account status from minio, I'm not sure if it's possible to get more information populated here.
As far as I can tell the secret is not available from the API.
`mc admin user info minio foo --json`
```json
{
"status": "success",
"accessKey": "foo",
"userStatus": "enabled"
}
```
`terraform import minio_iam_user.foo foo`
```
minio_iam_user.foo: Importing from ID "foo"... …
```

Support importing iam users, fixes #90

---

minio/resource_minio_iam_policy.go

Fixes #105 
Currently the update functionality of `minio_iam_policy` resources is not working when the policy property is updated. It silently fails, it appears to run successfully but the changes are never actioned so terraform apply is stuck in a permanent changes state.
Of the three properties of the resource `[name, name_prefix, policy]` policy is the only one which does not have the `forceNew` flag set.
However, inside the `minioUpdatePolicy`  function the code primarily handles changes to the name property, even though changes to that field will force the deletion and recreation of the resource.
The commit simplifies the update function, and focuses soley on the policy property, using the existing resource id as a reference to the resource on the minio api.
Although the minio api …

Fix update function of minio_iam_policy, ensuring policy gets updated

---

minio/check_config.go
minio/payload.go
minio/resource_minio_iam_user.go

This enables documenting legacy users without having to rotate passwords.
Techniques like eYAML / git-crypt / KMS / sops / .. can still provide the layer of  secrecy needed by the project.

Add possibility to specify IAM User secretes

---

.github/workflows/go.yml
.gitpod.yml

* Install a specific version of Go and Terraform, which we know that are working.
* Update GitHub action to install Task, as the previous was deprecated. This fixes this warning:

Fix GitHub Action "Checkup"

---

.github/workflows/release.yml

* Updates to the latest `import-gpg` GitHub action.
* Switches from slightly outdated fork to the original repository.
* Allows signing-only keys in releases.

Switch to original import-gpg GitHub action

---

renovate.json

* Sets 'packageRules' and 'dependencyDashboard' settings for Renovate Bot. As we're running tests automatically on each Pull Request, it's fine to auto-merge dependencies patches when all the tests are passing.
- https://docs.renovatebot.com/configuration-options/#automerge

Allow Renovate Bot to auto-merge patches (or lower-level) dependencies updates

---

README.md
go.mod

* Update Go Version references because the newer version is required to build for "darwin_arm64". Also because in all other files we're already using Go v1.16.

Update Go Version references from "1.15" to "1.16" as the newer version is required to build for darwin_arm64

---

.gitpod.yml
Taskfile.yml

This PR includes the following changes:
* Speeds up the startup of Gitpod by making use of [Prebuilds](https://www.gitpod.io/docs/prebuilds/), and add two IDE extensions to work with the Go and Terraform files out of the box.
* Updates the plugin version on `Taskfile.yml`. This version number is used only in local builds during development. The builds generated by GoReleaser use a version obtained from the latest git tag instead.

Add 'init' instructions to make use of Gitpod Prebuilds

---

.gitpod.yml

* Add instructions to install and configure [MinIO Client](https://docs.min.io/docs/minio-client-complete-guide) on Gitpod instance, to make it easy to debug the MinIO Local Server.

Make also MinIO Client available on Gitpod Instance

---

.gitpod.yml

- Ignore port 9001 used by MinIO Server Console, when opening the project on Gitpod, as this port is not meant to be opened in a browser.

Update Gitpod configuration

---

README.md
minio/check_config.go
minio/new_client.go
minio/payload.go
minio/provider.go

Allows connecting to servers with a self-signed certificate.

Add ca file

---

go.mod
go.sum
minio/resource_minio_iam_policy.go
minio/resource_minio_s3_bucket_policy.go
minio/resource_minio_s3_bucket_policy_test.go

Updates dependencies to use [hashicorp/awspolicyequivalence](https://github.com/hashicorp/awspolicyequivalence/) to ignore sort order inside policy JSON objects. It looks like it's a fork of the previous dependency used to fix the same issue in [hashicorp/terraform-provider-aws](https://github.com/hashicorp/terraform-provider-aws/blob/29acd34f0990be296fef732f81ae69cab43a8a78/go.mod#L15).
I also added one small test to the test file added in #165. Happy to make any changes to this
- Closes: #117

Ignore aws policy sort order for diffs

---

Taskfile.yml
minio/import_minio_s3_buckets.go
minio/payload.go
minio/public_policy.go
minio/public_policy_test.go
minio/public_read_policy.go
minio/readonly_policy.go
minio/readonly_policy_test.go
minio/readwrite_policy.go
minio/readwrite_policy_test.go
minio/resource_minio_s3_bucket.go
minio/resource_minio_s3_bucket_test.go
minio/writeonly_policy.go

Add bucket import handling to not force bucket recreation due to changes in the `acl` field.
* Fixes #89
* Fixes #65
The way `mc` (or ration `minio`) detects the `acl` name is... horrible?  But I think this way could work.  I'm not sure about using the `minio` internals inside `payload.go` is wanted..  It's already used for `StringSet`, so I *think* it should be ok?
The tests are good, but I haven't run it for real yet.

Bucket import acl

---

docs/resources/s3_object.md
examples/resources/minio_s3_object/main.tf
examples/resources/minio_s3_object/resource.tf
examples/resources/minio_s3_object/variables.tf

This is a follow-up for PR #236, which added support for setting the `content_type` for `minio_s3_object`.

Update `minio_s3_object` resource example

---

renovate.json

* To reduce the update load, let's update the aws sdk less often.
* Idea from https://docs.renovatebot.com/configuration-options/#packagerules

renovate, update aws-sdk less often

---

.gitpod.yml
README.md

[It's known](https://github.com/aminueza/terraform-provider-minio/issues/259#issuecomment-1210605079) that the provider is running fine with the latest version of Terraform (v1.2), so we should update the Readme.
Also, this PR updates the Gitpod environment configuration to use the latest Terraform version (installed via Homebrew).

Use latest version of Terraform and update Gitpod configuration

---

docs/resources/s3_bucket.md
minio/resource_minio_s3_bucket.go

1. Fixes typos
2. Allows setting `quota` (data limit) on bucket resource
3. Generates bucket resource docs
- Resolves: #257
- See also: pulumi/pulumi-minio#37
@BuJo agreed to review
- Closes:  #257

Add ability to set bucket quota on bucket resource

---

docs/resources/s3_bucket.md
examples/bucket/bucket.tf
minio/resource_minio_s3_bucket.go
minio/resource_minio_s3_bucket_policy_test.go
minio/resource_minio_s3_bucket_test.go

Form and expose the `arn` attribute for the bucket resource.
This makes it easier to create IAM policies.

Add `arn` attribute to the `minio_s3_bucket` resource

---

docs/index.md
minio/provider.go

- Adds `minio_insecure` documentation.
- Reformat index.md following markdownlint rules.
Follow-up on #157, just adds documentation of `minio_insecure`. I noticed other issues regarding the CACERT variables so I left those out to avoid adding confusion until that's fixed.

Add minio_insecure to docs

---

minio/resource_minio_s3_bucket.go

Bucket ACLs can be changed on-the-fly, and are updated with a dedicated API call. No need to recreate the whole bucket.
Fixes #351

Don't force a re-creation on ACL change

---

Taskfile.yml

To get rid of the static version number on `Taskfile.yml`.
To test, run `task install` and confirm if the version is set correctly in the path where the plugin is saved. For example:
```
❯ task install
Building and installing plugin in /home/gitpod/.local/share/terraform/plugins/registry.terraform.io/aminueza/minio/1.6.0/linux_amd64/terraform-provider-minio
Done!
```

Use the plugin version from the latest available repository tag when running tasks

---

README.md

Because we now target many more architectures. See the [last release](https://github.com/aminueza/terraform-provider-minio/releases/tag/v1.6.0), for example.

Avoid mentioning specific architectures of prebuilds on Readme

---

examples/serviceaccount/main.tf

As mentioned here: https://github.com/aminueza/terraform-provider-minio/pull/355#discussion_r996281863

Use a loose version requirement, to make it runnable with the development version built with "task install" command

---

docs/index.md
minio/check_config.go
minio/new_client.go
minio/payload.go
minio/provider.go

Adds `minio_session_token` configuration option to support using temporary credentials. I followed the recommended strategy from the issue comment, and I also updated the `minioAdmin` creation to use `NewWithOptions` to support configuring credentials with a session token. I didn't see anywhere else that needed updating, but I may have missed something.
The tests are passing, but I'm happy to add more. I just didn't see a clear place where provider configuration tests would fit. Let me know if there are any changes I should make, thanks!
- Closes: #100

Add minio_session_token configuration

---

examples/bucket/bucket.tf
examples/user/output.tf

Two examples are failing to run when we execute `terraform init && echo "yes" | terraform apply` in their folders:
- `examples/bucket`
- `examples/user`
This PR fixes them.
It also auto-formats the content of `examples/bucket/bucket.tf`.

Fix 'bucket' and 'user' examples

---

.github/workflows/go.yml
.gitpod.yml
README.md

- Updates terraform to version 1.3.3 in `.github/workflows/go.yml`
- Updates terraform version in Readme
- Updates a deprecated command in  `.gitpod.yml`
---
Although the provider still works fine for v1.2, I think we should stick with what's mentioned in the Readme:
https://github.com/aminueza/terraform-provider-minio/blob/eaa16871b3b6191f1a0454c2bad12b4d8e5a6e8e/README.md?plain=1#L52-L53
My concern is that someone willing to contribute could get demotivated to contribute to a project that requires backward compatibility. (I've seen a lot of problems with this aspect in other libraries/plugins/extensions projects.)

Update terraform to v1.3

---

minio/check_config.go
minio/resource_minio_service_account.go
minio/resource_minio_service_account_test.go

Fixes problems unearthed by changes in #364
Changes:
* Use `ForceNew` on target user changes.  This just simplifies the code.
* Fix the test if the service account can log in.  This check cannot happen using the GUI, as service accounts can not log into it that way.  This rewrites the check to simply list all buckets and checks success.  It works by using the admin `minio` user as target user, which also removes the oddity of using a non-existent target user in the tests.
* Revise logic around failures deleting the service account, which could lead to hiding the real error.

Fix service account login

---

docs/resources/s3_bucket_versioning.md
minio/payload.go
minio/resource_minio_s3_bucket_versioning.go
minio/resource_minio_s3_bucket_versioning_test.go

Adds `exclude_folders` and `excluded_prefixes` fields to `minio_s3_bucket_versioning` resource to cover missing functionality. Initially I'd planned on including `mfa_delete` as well because it's in the client, but after some initial troubleshooting it looks like it isn't currently supported on the server:
https://github.com/minio/minio/blob/52221db7ef4944fa0a2e0b133c760687ca8fe66e/internal/bucket/versioning/versioning.go#L53
The other fields look like they're working fine though, but wanted to flag that
- Closes #370

Add fields to minio_s3_bucket_versioning

---

minio/resource_minio_iam_user.go
minio/resource_minio_iam_user_test.go

Changes
- Fixes the issue with updating `name` on `minio_iam_user` by using `ForceNew` for deleting and replacing a user when the username changes
- Refactors `minio_iam_user` to remove the custom logic that previously managed replacing a user when the username changedIt 
- Adds a test to verify that updating `name` for `minio_iam_user` runs successfully, which fails on the current code
- Closes #377

Fix updating minio_iam_user name

---

minio/resource_minio_iam_group.go
minio/resource_minio_iam_group_test.go

- Updates the read operation for `minio_iam_group` to use `d.Id()` instead of referencing the group config so that importing works
- Updates the associated test to check whether or not import works by adding a step with `ImportState`
While updating this I noticed that the behavior of using a hidden `group_name` field in addition to `name` as well as only reading `group_name` in `minioReadGroup` seemed a bit odd. For now I just ignored the fields that aren't read to match the pattern from other test files. Would it make sense to refactor that in the future or am I missing something in the implementation?
- Closes: #375

Fix importing minio_iam_group

---

README.md

From this:
To this:
Reason: https://github.com/badges/shields/issues/8671

Update GitHub Workflow Status Badge

---

docs/resources/ilm_policy.md
minio/resource_minio_ilm_policy.go
minio/resource_minio_ilm_policy_test.go

Adds support for `DeleteMarker` to `minio_ilm_policy` based on the [documentation from the issue](https://github.com/minio/minio/blob/master/docs/bucket/lifecycle/README.md#33-automatic-removal-of-delete-markers-with-no-other-versions) #384.
Adding `DeleteMarker` seemed simpler within the current setup than adding a new block, so I followed the pattern currently in place. I'm planning on looking into `NoncurrentVersionExpiration` in a separate PR
- Progress on #384

Add delete marker support to minio_ilm_policy rules

---

docs/resources/ilm_policy.md
minio/resource_minio_ilm_policy.go
minio/resource_minio_ilm_policy_test.go

* Add a "tags" argument to the "rule" block, to set the tags of the rule filter
* Following the [S3 docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-configuration-examples.html), this PR implements the different XML formatting when using "filter" argument only (prefix), and when using "tags" with it
* Add acceptance tests for these two cases
- See also: #384

Add support for Tags in minio_ilm_policy resource

---

.github/workflows/docs.yml
README.md

I noticed that in #421 there are some issues with the link validation action originally added in #43. It looks like there's a more actively maintained action that performs the same task that might be a better fit

Change github action for markdown link checks

---

.github/workflows/go.yml

Add `repo-token` to avoid this API Limit Reached error: https://github.com/aminueza/terraform-provider-minio/actions/runs/4511651319/jobs/7944054765
Reference: https://github.com/arduino/setup-task#repo-token

Add `repo-token` to avoid API Limit Reached error

---

docs/resources/s3_bucket.md
minio/check_config.go
minio/payload.go
minio/resource_minio_s3_bucket.go
minio/resource_minio_s3_bucket_test.go

This PR implements the option to enable object locking with `minio_s3_bucket` resource type. There's a new option `object_locking`, that can be specified for these resources.
Default behavior did not change, and object locking defaults to false.
- Resolves: #452

Add support for object locking in minio_s3_bucket resource.

---

minio/resource_minio_s3_bucket.go

Fixes https://github.com/aminueza/terraform-provider-minio/issues/459

Avoid forcing replacement of the bucket when setting a value for `object_locking`

---

examples/resources/minio_ilm_policy/resource.tf

The `expiration` must be a duration, or "DeleteMarker" and can't be set `int`. https://github.com/aminueza/terraform-provider-minio/blob/85e98aa33b9ca0153a37df98fd8808f2776bddc1/minio/resource_minio_ilm_policy.go#L70-L72

Fix an example value of `expiration`

---

minio/resource_minio_iam_group.go

This PR fixing the issue in the resource `minio_iam_group`.
`disable_group` option did not work correctly, it did not update the group status in the MinIO, even if you set it to true or false. 
- Resolves: #483
- Closes: #483

Fix group status handling

---

minio/resource_minio_iam_group_policy_attachment.go
minio/resource_minio_iam_user_policy_attachment.go
minio/utils.go

- Do not override existing attached group/user policies
- Resolves #331

add multiple group/user policies support

---

minio/resource_minio_iam_group_policy_attachment.go
minio/resource_minio_iam_user_policy_attachment.go
minio/utils.go

- Use locks to prevent concurrent policy attachments on same user/group
- Resolves: #494 
- Closes: #494

fix minio_iam_user_policy_attachment: Error: Provider produced inconsistent result after apply (fix #494)

---

minio/resource_minio_iam_policy.go

Policy names are not allowed to contain a colon (:) in the name. This is allowed by the Minio webinterface and is used by SSO to reference claims.
1. Add a policy resource
```terraform
resource "minio_iam_policy" "test" {
name = "urn:test:bucketname"
policy= <<EOF
{
"Version":"2012-10-17",
"Statement": [
{
"Sid":"ListAllBucket",
"Effect": "Allow",
"Action": ["s3:PutObject"],
"Principal":"*",
"Resource": "arn:aws:s3:::*/*"
}
]
}
EOF
}
```
2. Run a terraform plan
3. Results in error:
```
Error: "name" must match [\w+=,.@-]
│
│   with minio_iam_policy.test,
```
**Expected behavior:** 
The resource should be created with the use of colons
**Actual behavior:**
The policy resource is not created, but the error occurs
**Reproduces how often:**  100%
1.17.1
Minio allows the creation of policies …

Allow colons in policy name

---

docs/resources/iam_service_account.md
examples/serviceaccount/serviceaccount.tf
minio/check_config.go
minio/payload.go
minio/resource_minio_service_account.go
minio/resource_minio_service_account_test.go

- Adds policy field to minio_iam_service account
- Resolves: #501

Add policy field to minio_iam_service account

---

.github/CONTRIBUTING.md
README.md
go.mod
main.go

As the repository has been moved to an organization, we should update all URLs to use the organization name.
Note that this PR doesn't change the [Provider name in Terraform registry](https://registry.terraform.io/providers/aminueza/minio).

Update repository URL

---

minio/resource_minio_s3_bucket.go
minio/resource_minio_s3_bucket_versioning_test.go

Load all object versions when trying to clear out objects when `force_destroy` is set on a bucket. Previously this did not incorporate versions, so versioned objects would not all be deleted and cause destruction to fail.
Quick note that the test isn't great here, essentially just making sure we can delete a bucket with versioning and `force_destroy`, but I'm running into errors without logs when I include `minio_s3_object` resources and update them. Open to suggestions there, but wanted to add some testing to be safe.
- Closes: #509

Destroy object versions on bucket force_destroy

---

.github/workflows/release.yml

Update goreleaser-action to v5 and add permission for the workflow to attach binaries to GitHub Releases.
Reference: https://github.com/goreleaser/goreleaser-action?tab=readme-ov-file#workflow
Note for the reviewer: The updated workflow [has been tested here](https://github.com/terraform-provider-minio/terraform-provider-minio/actions/runs/6274593669/job/17040285415), and it [successfully released the provider version 1.18.1](https://github.com/terraform-provider-minio/terraform-provider-minio/releases/tag/v1.18.1).

Update goreleaser-action to v5 and add permission for the workflow to attach binaries to GitHub Releases

---

docs/resources/ilm_policy.md
minio/resource_minio_ilm_policy.go
minio/resource_minio_ilm_policy_test.go

Adds noncurrentversionexpiration to minio_ilm_policy to support this option:
[Minio-go](https://github.com/minio/minio-go/blob/master/pkg/lifecycle/lifecycle.go#L50
)
New parameters will look like this:
```
resource "minio_ilm_policy" "bucket-lifecycle-rules" {
bucket = minio_s3_bucket.bucket.bucket
rule {
id = "expire-noncurrentversion-7d"
noncurrent_version_expiration_days = "7"
}
}
```
Actually expired objects on versioned buckets are never deleted
- Closes: #523

Add Noncurrent Version expiration to ilm policy

---

minio/resource_minio_service_account.go
minio/resource_minio_service_account_test.go

Adds `disable_user` and `target_user` to `minio_service_account` on import which were previously missing. The more important one is `minio_service_account`, but in case `disable_user` presented issues I added it as well. `disable_user` is not checked for errors since it's pulled from the account status which is already checked.
I didn't include `secret_key` because it's computed and unless I'm misunderstanding the implementation wouldn't be necessary here.
I may have missed things in the implementation, happy to make changes!
- Closes: #481

Add service account values to read and import

---

.github/workflows/go.yml

As we already stated it's supported, in the Readme.
https://github.com/aminueza/terraform-provider-minio/blob/f4464e51005c4cfd203e2357294311d912702911/README.md?plain=1#L44-L46

Update terraform version to 1.5.7 in GitHub Action

---

minio/resource_minio_ilm_policy.go
minio/resource_minio_ilm_policy_test.go

Fixes an issue where null expiration dates were getting set in the state as `0001-01-01` instead of `nil`, causing an update for every plan or apply.
- Resolves: #543
- Closes: #543

Fix null expiration date handling

---

.github/workflows/go.yml
minio/resource_minio_ilm_policy.go
minio/resource_minio_ilm_policy_test.go

Cherry-picking these two commits to `v1` branch:
- Fix null expiration date handling (#545)
- Update terraform version to 1.5.7 in GitHub Action (#540)

Preparation for Release v1.20.1

---

docs/resources/iam_group_policy_attachment.md

- PR fixes a small copy and paste typo in the provider resource docs for `minio_iam_group_policy_attachment`, where in the example usage the parameter `user_name` instead of `group_name` was used
- Registry Link: [iam_group_policy_attachment](https://registry.terraform.io/providers/aminueza/minio/latest/docs/resources/iam_group_policy_attachment)

Fixed group policy assign parameter typo

---

minio/resource_minio_ilm_policy.go

There was no mention for how to expire delete markers in the Terraform docs, this change rectifies it.
- Resolves: #557

Document `DeleteMarker` expiry in ilm policy

---

go.mod
go.sum
minio/resource_minio_s3_object.go

Only 'content' and 'content_base64' have been implemented sofar, this PR adds 'source' support for resource_minio_s3_object, derived from https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/s3/bucket_object.go#L388-L405
- Resolves: #552
- Closes: #552

Add resource_minio_s3_object 'source' support

---

minio/resource_minio_service_account.go
minio/resource_minio_service_account_test.go

The recent change in #525 to track `target_user` in state for `minio_service_account` is breaking for LDAP users. It looks like `madmin` is returning `ParentUser` as a full LDAP string such as `"CN=minio-user,DC=example,DC=org"` for `minio-user`.
This PR fixes that issue by attempting to parse each returned `ParentUser` string as an LDAP string, and if it fails return the string as-is. I saw some regex utilities for checking whether or not a string was LDAP, but it didn't look like they helped much with parsing, and since this ignores non-LDAP strings it felt simple enough to do this simply.
My big question is that I'm not sure how to test it other than the unit tests here. It looks like we don't have a ton of tools for testing LDAP users, so another set of eyes would be helpful
- …

Parse service account user from LDAP str

---

minio/resource_minio_iam_group.go
minio/resource_minio_iam_group_test.go
minio/resource_minio_iam_user.go
minio/resource_minio_iam_user_test.go

Minio recently changed behaviour by using case sensitive ldap queries. This makes it necessary to specify the distinguished name for user/group policy attachments exactly in the same case as the server.
This merge request updates the validation regex to allow for lowercase LDIF field names in the dn (e.g. CN=foo vs cn=foo).
The relevant Minio MR: https://github.com/minio/minio/pull/19358
As an alternative the regex could be made case insensitive with `(?i)^...` but then also something like `Cn=foo` or `cN=foo` would be valid.

fix: Allow for lowercase token in ldap dn

---

docs/resources/ilm_tier.md
minio/resource_minio_ilm_tier.go

- fix Azure and GCP remote tier creation and add support for tier options
- Fix Azure remote tier creation: the account name was not used properly and prevented the creation
- Fix GCP remote tier creation: providing the credentials json made the provider crash
- Support all remote tier options like region, storage class and prefix: previously theses were read but not created
Theses changes were tested with Azure and GCP sadly I don't have access to an AWS account to try out the changes.

fix Azure and GCP remote tier creation and add support for tier options

---

minio/resource_minio_iam_policy.go
minio/resource_minio_iam_policy_test.go

Currently the  provider has very annoying bug: if an IAM policy was removed externally, plan fails and the project that contains minio policies becomes unplannable.
- Added code that handles the `XMinioAdminNoSuchPolicy` error code, similar to how it is [handled in the minio_iam_user resource](https://github.com/aminueza/terraform-provider-minio/blob/d738dd082cc09d1f6b63ad5ac2686ac229d52df1/minio/resource_minio_iam_user.go#L154).
- Added a unit test validating the corrected behavior
The new behavior:
```bash
$ terraform plan 
minio_iam_policy.test_policy: Refreshing state... [id=state-terraform-s3]
Note: Objects have changed outside of Terraform
Terraform detected the following changes made outside of Terraform since the last "terraform apply":
- …
```

fix: Handle case when IAM Policy was deleted externally

---

minio/resource_minio_ilm_tier.go

- Pass the `endpoint` argument to the MinIo client if the S3 tier is being used.
Resolves #570
@george-zubrienko, FYI
- Closes: #570

fix: Add the endpoint property to Amazon S3 config

---

minio/data_source_minio_s3_object.go
minio/provider.go

- Add the `minio_s3_object` data source.

feat: add minio_s3_object data source

---

minio/resource_minio_ilm_tier.go

- Fix to GCS ilm tier creation, region is using the prefix value instead of the region value.
- Resolves: #574 
- Closes: #574

fix: gcs ilm tier region using prefix string instead of region string

---

.github/workflows/go.yml
README.md
minio/resource_minio_ilm_tier.go

When terraform performs an import of a resource only the `id` property is available in the provider context. But the `minio_ilm_tier` resource uses the `name` property to get the tier from MinIO api (which is empty) and import of the ilm tier fails.
- Use the `id` context property instead of `name` for reading the `minio_ilm_tier` resource
Resolves #578

fix: use the id property instead of name for read ilm tier

---

docker-compose.yml
examples/bucket/main.tf
examples/group/main.tf
examples/policy/main.tf
examples/resources/minio_s3_bucket_replication/main.tf
examples/resources/minio_s3_object/main.tf
examples/serviceaccount/main.tf
examples/user/main.tf
go.mod
main.go

As there was a [breaking change](https://github.com/aminueza/terraform-provider-minio/pull/588).

Update module to v3

---

docs/resources/iam_service_account.md
examples/serviceaccount/serviceaccount.tf
minio/check_config.go
minio/payload.go
minio/resource_minio_service_account.go
minio/resource_minio_service_account_test.go

Allows setting 3 new attributes on service accounts:
- name: optional string
- description: optional string
- expiration: optional date, in RFC3339 format
All of these fields are optional, making it backward compatible.
Users may see a change on expiration from `null` to `1970-01-01T00:00:00Z` (which are equivalent), but only if something else is updated. As far as I know there is no way around this, since Terraform considers `null` as untracked while Minio sees it as either epoch for creations and as `no change` for updates.
I've included argument validation matching Minio's API requirements: 
- name must be 32 bytes max
- description must be 256 bytes max
- expiration must be between +15mn and +1y
Allowing invalid values to be sent to the API would throw relatively unclear errors, …

Add name, description and expiration support for service accounts

---

minio/resource_minio_s3_bucket.go

- Allow for an empty bucket ACL (`private`). If the ACL is an empty string, `minio-go` removes the policy, making it a private ACL. Prior to this change, setting the ACL to `private` would result in a no-op.

Fix setting private bucket ACL

---

.github/workflows/close-stale-issues-and-pull-requests.yml

Implements automated housekeeping for inactive issues and PRs:
- Issues marked stale after 30 days, closed after 7 more days
- Pull requests marked stale after 60 days, closed after 7 more days
- Daily check at 14:00 UTC
- Custom warning messages before closure
This helps maintain repository cleanliness by reducing open but inactive items.

Add GitHub Action to automatically close stale issues and pull requests

---

minio/check_config.go
minio/error.go
minio/new_client.go
minio/provider.go
minio/resource_minio_iam_group_membership.go

- New `ConfigError` and `ResourceError` types for better error handling
- Helper function `getOptionalField` for consistent configuration management
- Input validation for API version
- Improved SSL/TLS configuration with dedicated helper methods
- Error messages with more context
- Improved documentation for provider schema and functions
- Better organization of provider resources by category
- More consistent handling of optional configuration values
- Fixed typo in `IAMGroupMembershipConfig` function name
- Improved SSL/TLS configuration handling
- Added minimum TLS version requirement (TLS 1.2)
- Better certificate validation
- No breaking changes to the provider's public API
- All changes maintain backward compatibility
- Internal improvements focus on reliability and maintainability …

Improve the provider's configuration handling, error management, and code organization

---

.github/workflows/go.yml
Taskfile.yml
docker-compose.yml
docs/resources/accesskey.md
examples/accesskey/main.tf
minio/provider.go
minio/resource_minio_accesskey.go
minio/resource_minio_accesskey_test.go
minio/resource_minio_iam_user_test.go
minio/resource_minio_s3_bucket_test.go

This PR introduces a new Terraform resource, `minio_accesskey`, enabling users to manage MinIO access keys natively through Terraform. The implementation leverages the MinIO Admin Go SDK (`madmin-go`) to interact with the MinIO Service Account API, providing a robust and reliable alternative to shelling out to the `mc` CLI.
- **Create, Read, Update, Delete (CRUD) Operations:**  
Manage MinIO access keys programmatically for any user, including creation, status updates (enable/disable), and deletion.
- **Custom and Auto-Generated Credentials:**  
Supports both user-specified (`access_key`, `secret_key`) and auto-generated credentials.
- **Status Management:**  
Enable or disable access keys directly from Terraform using the `status` attribute.
- **Import Support:**  
Existing access keys …

Add `minio_accesskey` Terraform Resource for Managing MinIO Access Keys

---

minio/resource_minio_iam_policy.go
minio/resource_minio_iam_policy_test.go
minio/resource_minio_s3_bucket_policy.go
minio/resource_minio_s3_bucket_policy_test.go
minio/utils.go

This PR fixes #348 where MinIO IAM policies are marked as "updated-in-place" on every `terraform apply` run even when no actual changes occurred.
When applying IAM policies, Terraform detects a change on every run due to non-semantic differences between the stored policy and the policy returned by the MinIO API. These differences include:
- Different ordering of elements in arrays
- Whitespace and formatting variations
- JSON structure differences with identical semantic meaning
The solution implements semantic policy comparison using the `hashicorp/awspolicyequivalence` package:
1. Added a new utility function `NormalizeAndCompareJSONPolicies` that:
- Compares policies based on their semantic meaning rather than exact string matching
- Returns the existing policy when equivalent …

Improve IAM policy comparison to prevent unnecessary updates for equivalent policies

---

docs/resources/s3_bucket_replication.md
examples/resources/minio_s3_bucket_replication/resource.tf
minio/resource_minio_s3_bucket_replication.go
minio/resource_minio_s3_bucket_replication_test.go

This PR is the first part of resolution of the issue #629 and introducing the following change: renaming `bandwidth_limit` back to `bandwidth_limt` which was incorrectly renamed in #623.
Renaming the optional field leads to an inability to plan a terraform configuration if the `minio_s3_bucket_replication` resource was created in versions prior to `3.4.0` with provider versions later than `3.4.0`.
The plan to fix this issue consists of two steps:
1. Rename `bandwidth_limit` back to `bandwidth_limt` and release as version `3.5.1`
2. Mark `bandwidth_limt` as obsolete, add the new `bandwidth_limit` attribute and implement migration logic and release as version `3.5.2` See comments in the issue: https://github.com/aminueza/terraform-provider-minio/issues/629#issuecomment-2862509136
This pull …

Rename `bandwidth_limit` back to `bandwidth_limt`

---

.github/workflows/release.yml

Reference: https://goreleaser.com/deprecations/#-rm-dist
As seen [here](https://github.com/aminueza/terraform-provider-minio/actions/runs/15020645228/job/42208770091):

Replace the `--rm-dist` goreleaser argument with `--clean`

---

minio/utils.go

- Follow-up from https://github.com/aminueza/terraform-provider-minio/pull/632
Fix the error happening in the GoRelease script [[1](https://github.com/aminueza/terraform-provider-minio/actions/runs/15020645228/job/42208770091)]:
```
Error: minio/utils.go:229:104: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to log.Printf (overflows)
```

Avoid the integer overflow in the bandwidth limit warning message

---

examples/resources/minio_iam_user_policy_attachment/main.tf
examples/resources/minio_iam_user_policy_attachment/variables.tf
minio/resource_minio_iam_user_policy_attachment.go

Resolves #614
Since the policy attachment in the MinIO API is an attribute of the user, we consider that if the user is removed, the policy attachment is removed as well.
Added the `main.tf` and `variables.tf` to the `iam_user_policy_attachment` example to make it runnable with docker-compose stack from the repo.

Consider the attachment resource as removed if the user is removed

---

docs/resources/accesskey.md
minio/resource_minio_accesskey.go

- Resolves #638
As pointed out by @devsadds, MinIO has no max length enforcement for secret keys [[1](https://github.com/minio/minio/blob/a6c538c5a113a588d49b4f3af36ae3046cfa5ac6/internal/auth/credentials.go#L47-L50)].
Note that the auto-generated key is by default 40 characters on MinIO, so it is on terraform-provider-minio and will remain like that.
This PR is just a patch to remove the max length limit.

Remove the max length enforcement for secret keys

---

minio/resource_minio_ilm_policy.go

This change resolves an issue where applying an minio_ilm_policy fails on S3-compatible services like Hetzner Object Storage when no lifecycle policy is present on the bucket.
The provider currently fails with the error: Error: failed to get existing lifecycle: Error response code NoSuchLifecycleConfiguration.
This PR updates the isNotFoundError check to correctly identify NoSuchLifecycleConfiguration as a "not found" condition, allowing the provider to proceed as expected.

fix(ilm): Treat NoSuchLifecycleConfiguration as not found

---

minio/resource_minio_accesskey.go

- Removed `GetUserInfo` check in `minioCreateAccessKey` to allow access key 
creation for the root user, relying on `AddServiceAccount` for validation.
- Added `ForceNew: true` to the `user` field in the schema. Since MinIO's `UpdateServiceAccount` cannot modify the `TargetUser`, this ensures that changing the `user` field triggers resource recreation, which validates the new user via `AddServiceAccount`.
- Resolves: #650
@felladrin

Fix root user access key creation and make user field immutable

---

minio/resource_minio_accesskey.go

**Before**:
- Always updated both status and policy regardless of actual changes
- Single `UpdateServiceAccount` call with both fields
- Less granular error reporting
**After**:
- Only updates fields that have actually changed
- Separate `UpdateServiceAccount` calls for status and policy changes
- More accurate error reporting with context about which field failed to update

Split accesskey updates into separate status and policy operations
