aminueza/terraform-provider-minio

- docker-compose.yml
- minio/payload.go
- minio/public_policy_test.go
Fixes regarding #7 issue:
* Updated Minio-api to v2;
* Updated Minio docker version;
* Fixed `unsupported action 's3:GetBucketLifecycle'` error.
> fix: iam permission public policy

- minio/check_config.go
- minio/payload.go
- minio/provider.go
- minio/resource_minio_iam_group.go
Part of the resolution for issue #2.
> Add initial implementation for MinIO Groups management

- examples/bucket.tf
- minio/check_config.go
- minio/payload.go
- minio/public_policy.go
- minio/public_policy_test.go
- minio/readonly_policy.go
- minio/readonly_policy_test.go
- minio/readwrite_policy.go
- minio/readwrite_policy_test.go
- minio/resource_minio_bucket.go
- minio/writeonly_policy.go
* Add resource to manage buckets
> Manage buckets

- minio/provider.go
- minio/resource_minio_iam_group_policy_attachment.go
- minio/resource_minio_iam_user_policy_attachment.go
Issue #22:
* add group policy attachment;
* fix fmt issue;
* fix typos.
> add group policy attachment

- docs/IAM_GROUP.md
- docs/IAM_GROUP_MEMBERSHIP.md
- docs/IAM_GROUP_POLICY.md
- docs/IAM_GROUP_POLICY_ATTACHMENT.md
- docs/IAM_POLICY.md
- docs/IAM_USER.md
- docs/IAM_USER_POLICY_ATTACHMENT.md
- docs/S3_BUCKET.md
- go.mod
- go.sum
- minio/resource_minio_iam_user_policy_attachment.go
* Add new resources documentation;
* Fix typos.
> Add providers documentation

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
For more details, see <https://code.visualstudio.com/docs/remote/containers>.
> Add configuration for VS Code Dev Container

- docs/IAM_GROUP_USER_ATTACHMENT.md
- minio/check_config.go
- minio/payload.go
- minio/provider.go
- minio/resource_minio_iam_group_user_attachment.go
- minio/utils.go
Hi, 
For some UseCases i need a Resource for adding a User to a existing Group.
```
resource "minio_iam_group_user_attachment" "stash-backupusers" {
user_name  = minio_iam_user.minio_backup_user.name
group_name = var.minio_stash_backup_group_name
}
```
> Add new Resource for add a single user to a specific group

- .devcontainer/Dockerfile
And remove unnecessary instructions from the startup command.
> Download 'gopls' module fully updated

- .devcontainer/Dockerfile
> Update MinIO Docker image tag

- .github/workflows/go.yml
Trying to fix the 'stuck during the build' problem.
> Improve workflow

- README.md
- go.mod
- main.go
- minio/new_client.go
- minio/payload.go
- minio/resource_minio_iam_group.go
- minio/resource_minio_iam_group_membership.go
- minio/resource_minio_iam_group_membership_test.go
- minio/resource_minio_iam_group_test.go
- minio/resource_minio_iam_group_user_attachment.go
- minio/resource_minio_iam_user.go
- minio/resource_minio_iam_user_test.go
* Fix old module names;
Issue #63
> fix-mod typo

- go.mod
- go.sum
Via 'go mod tidy' command.
Reference: https://golang.org/ref/mod#go-mod-tidy
> Cleanup dependencies

- minio/resource_minio_s3_bucket.go
I guess this should be all that's needed to fix #87
> Add bucket ACL default value to match documentation, fixes #87

- README.md
This PR reverts the last change made on `README.md`.
> Revert the last change made on README.md

- minio/resource_minio_s3_object.go
Add missing `content_type` implementation.
- Resolves: #235
- Closes: #235
> Fix minio_s3_object content_type support

- minio/provider.go
* Use of minio_ssl field worked, but environment variable did not
* Closes #262
> Fix usage of environment variable MINIO_ENABLE_HTTPS

- CONTRIBUTING.md
There's no `AUTHORS.md` file so this line is confusing
> Remove reference to AUTHORS.md

- minio/resource_minio_iam_user.go
- minio/resource_minio_iam_user_test.go
- minio/resource_minio_service_account.go
This builds on #364 and tries to fix updating the user secret and retaining the current functionality.  Needs a helping (testing) hand.
> Tryfix user update secret

- minio/check_config.go
As I don't have the headspace right now for #296, I still want to fix #244 right now.  Patch is "obviously" correct, shouldn't blow up in our faces ;)  Forgive the lack of tests.
* fixes #244
> Fix using CA Cert File

- docs/index.md
- Resolves: #435
- Closes: #435
> Fix documentation environment variables

- minio/resource_minio_service_account.go
- minio/resource_minio_service_account_test.go
- Prevents dropping of default policy by applying empty policy if none is set
- Resolves: #517
> Handle empty service account policy

- minio/resource_minio_iam_user.go
- minio/resource_minio_iam_user_test.go
- Instead of failing on missing users, they are marked as non-existing and are recreated by terraform on apply.
- Resolves: #511
- Closes: #511
> feat: recreate user if not found anymore

- .github/CONTRIBUTING.md
- README.md
- go.mod
- main.go
This reverts commit 7a680c7d021e37100530c7b193c3d4af4e24394c.
> Revert "Update repository URL (#520)"

- .github/workflows/docs.yml
- .github/workflows/go.yml
- README.md
Required as the 'master' branch has been renamed to 'main'.
> Update main branch name

- minio/provider.go
- minio/resource_minio_s3_bucket.go
- minio/resource_minio_s3_object.go
- Improve description of some of the provider's fields
- Adds a description to some fields of `minio_s3_object` and `minio_s3_bucket` resources.
> docs: more extensive docs

- minio/resource_minio_service_account.go
Fix https://github.com/aminueza/terraform-provider-minio/issues/596
> Preserve custom policy when changing name or description of a service account

- minio/resource_minio_service_account.go
> Fix number of minutes in a year for service account expiration (#600)

- minio/resource_minio_s3_bucket.go
> Revert "Fix setting private bucket ACL (#607)"

- docs/resources/ilm_policy.md
- examples/resources/minio_ilm_policy/resource.tf
- minio/resource_minio_ilm_policy.go
- minio/resource_minio_ilm_policy_test.go
> Allow change status of a minio_ilm_policy

- docker-compose.yml
Update the docker container image of MinIO.
> Update MinIO version

- minio/resource_minio_ilm_policy.go
> Allow zero days in ILM policy expiration rule validation

- minio/resource_minio_accesskey.go
- minio/resource_minio_accesskey_test.go
The `minio_accesskey` resource in the Terraform provider was continuously trying to remove implied policies on every `terraform plan` or `terraform apply` cycle when a policy was attached to the parent user via `minio_iam_policy` and `minio_iam_user_policy_attachment`.
When a user has policies attached via `minio_iam_user_policy_attachment`, MinIO automatically creates an implied policy for any access keys belonging to that user. The provider was incorrectly treating these implied policies as explicitly managed policies, causing perpetual diffs as it tried to remove them.
Updated the `minioReadAccessKey` function in `resource_minio_accesskey.go` to check the `ImpliedPolicy` field from the `InfoServiceAccountResp` struct returned by the MinIO Admin API.
**File: …
> Prevent perpetual diffs by ignoring implied policies in MinIO access keys

- minio/resource_minio_s3_bucket_versioning.go
- minio/resource_minio_s3_bucket_versioning_test.go
- Resolves https://github.com/aminueza/terraform-provider-minio/issues/618
> Add bucket existence check to avoid issues when a bucket gets deleted manually
